user_check:
  max_name: 50
  max_email: 255
  min_password: 6
user:
  ava_size: 80
  gravatar_size: 50
per_page_user : 10
remember: "1"
set_time_expired: 2
content_max_length: 140
resize_to_limit:
  col: 400
  row: 400
picture_size: 5